workflows:
  ios-project: # workflow ID
    name: iOS project # workflow name
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - pwd
      - ls
      - xcodebuild build -scheme "CodeChallenge" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
