workflows:
  ios-project: # workflow ID
    name: iOS project # workflow name
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - xcodebuild build -project "CodingChallenge/CodingChallenge.xcodeproj" -scheme "CodingChallenge" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      - xcodebuild test-without-building -project "CodingChallenge/CodingChallenge.xcodeproj" -scheme "CodingChallenge" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11 Pro Max,OS=13.4' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
