workflows:
  ios-project: # workflow ID
    name: iOS project # workflow name
    environment:
      xcode: 11.4.1
      cocoapods: default
    scripts:
      #- xcodebuild build -project "CodingChallenge/CodingChallenge.xcodeproj" -scheme "CodingChallenge" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
      #- xcodebuild test -project "CodingChallenge/CodingChallenge.xcodeproj" -scheme "CodingChallenge" -destination 'platform=iOS Simulator,id=0D402FC5-D9D5-4862-8643-05EECA069998'
      - bundle exec fastlane unit_tests
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
